---
title: "201129_HumanCRPSCombined_RDP-Format-Demuxing-Metadata"
author: "Rachel Rodgers"
date: "`r Sys.Date()`"
output: html_document
---

```{r load-libraries, message=FALSE}
library("phyloseq")
library("readxl")
library("tidyverse")
```

```{r mappingFileList}
mappingFileList <- c("run1" = "mappingFile_190201.txt",
                     "run2" = "mappingFile_190318.txt",
                     "run3" = "mappingFile_190523.txt",
                     "run4" = "mappingFile_200127.txt",
                     "run5" = "mappingFile_201019_LaraC_V4_Mouse_Human_CRPS.txt")

mappingFiles <- map(paste0("../documents/RDP/", mappingFileList), read.delim, 
                    header = TRUE, sep = "\t", stringsAsFactors = FALSE,
                    check.names = FALSE)

names(mappingFiles) <- names(mappingFileList)
```

## Format RDP Data for Demuxing

```{r mapping-file-for-demultiplexing}
# Contains only the data necessary for demuxing.

# Find common column names among files
allColNames <- map(mappingFiles, names)
commonColNames <- Reduce(f = intersect, x = allColNames)

# For each mapping file, pull out these common columns and add a run column
trimmedMapFileList <- vector(mode = "list", length = length(mappingFiles))
  
for (i in 1:length(mappingFiles)) {
  
  currentRun <- names(mappingFiles)[i]
  currentMap <- mappingFiles[[i]]
  
  trimmedDF <- currentMap %>% 
    select(all_of(commonColNames)) %>% 
    mutate("run" = currentRun) %>% 
    select(`#SampleID`, BarcodeSequence, LinkerPrimerSequence, run, Description)
  
  trimmedMapFileList[[i]] <- trimmedDF
  names(trimmedMapFileList)[i] <- currentRun
  
}

# Combine the trimmed mapping files
combinedMap <- Reduce(f = rbind, x = trimmedMapFileList)

# Remove "CRPS Mouse", format the Description column, add other needed columns
# Correct Baldridge34A which should have Description "Acute", not "Control"
table(combinedMap$Description)
#combinedMap[combinedMap$`#SampleID` == "Baldridge34A", "Description"] <- "Acute"

combinedMapFmt <- combinedMap %>% 
  filter(Description != "CRPS mouse") %>% 
  mutate(Description = trimws(Description),
         Description = str_replace(Description, 
                                   pattern = " ", replacement = "_"),
         Sample_Type = case_when(Description %in% c("Acute", "Chronic") ~ "CRPS",
                                 Description == "Control" ~ "HHC",
                                 TRUE ~ Description),
         Sample_Status = case_when(Description %in% c("Acute", "Chronic") ~ "CRPS",
                                   Description %in% c("Control", "BioBank_Control") ~ "healthy",
                                   TRUE ~ Description)) %>% 
  select(`#SampleID`, BarcodeSequence, LinkerPrimerSequence, run, Sample_Type,
         Sample_Status, Description)

table(combinedMapFmt$Description)
```

```{r save-mappingFile_201129_Human_CRPS_Combined.txt, eval=FALSE}
write.table(combinedMapFmt, file = "../data/RDP/mappingFile_201129_Human_CRPS_Combined.txt",
            quote = FALSE, sep = "\t", row.names = FALSE)
```

